# Generated by Django 5.2 on 2026-08-17 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BannersItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_id', models.CharField(max_length=100)),
                ('photo_banner', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('url_link', models.CharField(max_length=100)),
            ],
        ),
    ]
