# Generated by Django 5.2 on 2026-08-19 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannersitem',
            name='banner_id',
            field=models.CharField(max_length=100, verbose_name='轮播标识'),
        ),
        migrations.AlterField(
            model_name='bannersitem',
            name='photo_banner',
            field=models.ImageField(upload_to='photos/%Y/%m/%d/', verbose_name='轮播图片'),
        ),
        migrations.AlterField(
            model_name='bannersitem',
            name='url_link',
            field=models.CharField(max_length=100, verbose_name='跳转链接'),
        ),
    ]
