# Generated by Django 5.2 on 2026-08-19 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_message_is_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='is_spam',
            field=models.BooleanField(default=False, verbose_name='垃圾信息'),
        ),
    ]
