# Generated by Django 5.2 on 2026-08-17 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradelist',
            name='is_sold',
            field=models.BooleanField(default=False, verbose_name='已下架/已售出'),
        ),
    ]
