# Generated by Django 5.2 on 2026-08-18 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_tradelist_is_sold'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradelist',
            name='series_number',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
