district_choices = {
    "Islands":"Islands",
    "Kwai Tsing":"Kwai Tsing",
    "North":"North",
    "Sai Kung":"Sai Kung",
    "Sha Tin":"Sha Tin",
    "Tai Po":"Tai Po",
    "Tsuen Wan":"Tsuen Wan",
    "Tuen Mun":"Tuen Mun",
    "Kwun Tong":"Kwun Tong",
    "Yuen Long":"Yuen Long",
    "Kowloon City":"Kowloon City",
    "Sham Shui Po":"Sham Shui Po",
    "Wong Tai Sin":"Wong Tai Sin",
    "Yau Tsim Mong":"Yau Tsim Mong",
    "Central & Western":"Central & Western",
    "Eastern":"Eastern",
    "Southern":"Southern",
    "Wan Chai":"Wan Chai",
}