<<<<<<< HEAD
# Generated by Django 5.2 on 2026-08-19 02:12
=======
# Generated by Django 5.2 on 2026-08-19 08:47
>>>>>>> ki2

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shoplist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopname', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('website', models.TextField(blank=True)),
                ('monday', models.CharField(blank=True, max_length=20)),
                ('tuesday', models.CharField(blank=True, max_length=20)),
                ('wednesday', models.CharField(blank=True, max_length=20)),
                ('thursday', models.CharField(blank=True, max_length=20)),
                ('friday', models.CharField(blank=True, max_length=20)),
                ('saturday', models.CharField(blank=True, max_length=20)),
                ('sunday', models.CharField(blank=True, max_length=20)),
                ('card_identification', models.BooleanField(default=False)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('shop_logo', models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/')),
            ],
        ),
    ]
