# Generated by Django 5.2 on 2026-08-18 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoplist',
            name='friday',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='shoplist',
            name='monday',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='shoplist',
            name='saturday',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='shoplist',
            name='shop_logo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='shoplist',
            name='sunday',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='shoplist',
            name='thursday',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='shoplist',
            name='tuesday',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='shoplist',
            name='wednesday',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
