# Generated by Django 5.2 on 2026-08-20 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0002_shoplist_district'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoplist',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='緯度'),
        ),
        migrations.AddField(
            model_name='shoplist',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='經度'),
        ),
    ]
