# Generated by Django 5.2 on 2026-08-20 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0003_shoplist_latitude_shoplist_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoplist',
            name='district',
            field=models.CharField(default='Unknown', max_length=50, verbose_name='分區'),
        ),
    ]
