# Generated by Django 5.2 on 2026-08-17 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer_comment', models.TextField(blank=True)),
                ('buyer_star', models.IntegerField(blank=True, null=True)),
                ('seller_comment', models.TextField(blank=True)),
                ('seller_star', models.IntegerField(blank=True, null=True)),
                ('is_public', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chat', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trading_record', to='contacts.chat')),
            ],
        ),
    ]
