# Generated by Django 5.2 on 2026-08-19 02:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Pokemon', 'Pokemon'), ('Energy', 'Energy'), ('Item', 'Item'), ('Supporter', 'Supporter'), ('Stadium', 'Stadium'), ('Tool', 'Tool')], default='pokemon', max_length=50)),
                ('photo_main', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('stage', models.CharField(blank=True, choices=[('Basic', 'Basic'), ('Stage 1', 'Stage 1'), ('Stage 2', 'Stage 2')], default='', max_length=50)),
                ('rarity', models.CharField(choices=[('C', 'C'), ('U', 'U'), ('R', 'R'), ('RR', 'RR'), ('ACE', 'ACE'), ('AR', 'AR'), ('SR', 'SR'), ('SAR', 'SAR'), ('UR', 'UR'), ('S', 'S'), ('SSR', 'SSR'), ('PROMO', 'PROMO')], default='', max_length=20)),
                ('title', models.CharField(max_length=50)),
                ('hp', models.IntegerField(blank=True, null=True)),
                ('energy_type', models.CharField(choices=[('Grass', 'Grass'), ('Fire', 'Fire'), ('Water', 'Water'), ('Lighting', 'Lighting'), ('Psychic', 'Psychic'), ('Fighting', 'Fighting'), ('Darkness', 'Darkness'), ('Metal', 'Metal'), ('Colorless', 'Colorless'), ('Fairy', 'Fairy'), ('Dragon', 'Dragon')], default='', max_length=50)),
                ('card_number', models.PositiveIntegerField()),
                ('transaction', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Generation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('total_cards', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Attack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('damage_value', models.PositiveIntegerField(blank=True, null=True)),
                ('damage_modifier', models.CharField(blank=True, choices=[('', 'Normal'), ('+', '+'), ('x', 'x')], default='', max_length=1)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attacks', to='cards.card')),
            ],
        ),
        migrations.CreateModel(
            name='Ability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abilities', to='cards.card')),
            ],
        ),
        migrations.CreateModel(
            name='Energy_Cost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('energy_type', models.CharField(choices=[('Grass', 'Grass'), ('Fire', 'Fire'), ('Water', 'Water'), ('Lighting', 'Lighting'), ('Psychic', 'Psychic'), ('Fighting', 'Fighting'), ('Darkness', 'Darkness'), ('Metal', 'Metal'), ('Colorless', 'Colorless'), ('Fairy', 'Fairy'), ('Dragon', 'Dragon')], max_length=50)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('attack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='energy_costs', to='cards.attack')),
            ],
        ),
        migrations.AddField(
            model_name='card',
            name='generation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cards', to='cards.generation'),
        ),
        migrations.CreateModel(
            name='Resistance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('energy_type', models.CharField(choices=[('Grass', 'Grass'), ('Fire', 'Fire'), ('Water', 'Water'), ('Lighting', 'Lighting'), ('Psychic', 'Psychic'), ('Fighting', 'Fighting'), ('Darkness', 'Darkness'), ('Metal', 'Metal'), ('Colorless', 'Colorless'), ('Fairy', 'Fairy'), ('Dragon', 'Dragon')], max_length=50)),
                ('resistance_value', models.PositiveIntegerField(blank=True, null=True)),
                ('resistance_modifier', models.CharField(blank=True, choices=[('', 'Normal'), ('+', '+'), ('x', 'x')], default='-', max_length=1)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resistances', to='cards.card')),
            ],
        ),
        migrations.CreateModel(
            name='Retreat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('energy_type', models.CharField(choices=[('Grass', 'Grass'), ('Fire', 'Fire'), ('Water', 'Water'), ('Lighting', 'Lighting'), ('Psychic', 'Psychic'), ('Fighting', 'Fighting'), ('Darkness', 'Darkness'), ('Metal', 'Metal'), ('Colorless', 'Colorless'), ('Fairy', 'Fairy'), ('Dragon', 'Dragon')], default='Colorless', max_length=50)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retreats', to='cards.card')),
            ],
        ),
        migrations.CreateModel(
            name='Weakness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('energy_type', models.CharField(choices=[('Grass', 'Grass'), ('Fire', 'Fire'), ('Water', 'Water'), ('Lighting', 'Lighting'), ('Psychic', 'Psychic'), ('Fighting', 'Fighting'), ('Darkness', 'Darkness'), ('Metal', 'Metal'), ('Colorless', 'Colorless'), ('Fairy', 'Fairy'), ('Dragon', 'Dragon')], max_length=50)),
                ('weakness_value', models.PositiveIntegerField(blank=True, null=True)),
                ('weakness_modifier', models.CharField(blank=True, choices=[('', 'Normal'), ('+', '+'), ('x', 'x')], default='x', max_length=1)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weaknesses', to='cards.card')),
            ],
        ),
    ]
