# Generated by Django 5.2 on 2026-08-20 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='category',
            field=models.CharField(choices=[('Pokemon', 'Pokemon'), ('Energy', 'Energy'), ('Item', 'Item'), ('Supporter', 'Supporter'), ('Stadium', 'Stadium'), ('Tool', 'Tool')], default='Pokemon', max_length=50),
        ),
    ]
